name: core_ui
description: Pacote compartilhado de UI, tema, widgets e DI global do WeGig
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.14.0
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.0.4
  geolocator: ^14.0.1
  http: ^1.2.2
  intl: ^0.20.1
  rxdart: ^0.28.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
